########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  annotations: {}

  cluster:

    cert:
      annotations: {}

    ingress:
      ingressClassName: ""

    istio:
      enabled: false
      gateway:
        selector:
          app: istio-ingressgateway

  debug: false

  image:
    pullPolicy: Always
    pullSecrets: []
    registry: docker.edu-sharing.com
    repository: projects/wlo

  metrics:
    scrape:
      interval: 10s
      timeout: 10s
    servicemonitor:
      enabled: false

  password: ""

  security: {}

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: nbp-connector

image:
  name: nbp-connector
  tag: ""

########################################################################################################################

replicaCount: 1

########################################################################################################################

service:

  port:
    api: 8080
    management: 8081

########################################################################################################################

ingress:

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-body-size: "5g"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "15"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"

  hosts:
    - nbp-connector.127.0.0.1.nip.io

  tls: []
  #  - secretName: nbp-connector-tls
  #    hosts:
  #    - nbp-connector.127.0.0.1.nip.io

  paths:
    - /

########################################################################################################################

config:

  auth:
    apiToken: ""

  nbp:
    source:
      slug: ""
    oAuth2:
      issuerUrl: https://aai.demo.meinbildungsraum.de/realms/nbp-aai
      clientId: ""
      clientSecret: ""

  jvm:
    ram:
      minPercentage: "90.0"
      maxPercentage: "90.0"

  metrics: true

  override: ""

  repository:

    baseUri: http://edusharing-repository-service:8080/edu-sharing
    username: ""
    password: ""
    timeout: 120000

########################################################################################################################

debug: false

########################################################################################################################

nodeAffinity: {}

tolerations: []

########################################################################################################################

podAnnotations: {}

podSecurityContext: {}

securityContext:

  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

########################################################################################################################

terminationGracePeriod: 120

startupProbe:

  failureThreshold: 30
  initialDelaySeconds: 0
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 10

livenessProbe:

  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 10

readinessProbe:

  failureThreshold: 1
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 10

########################################################################################################################

resources:

  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi

########################################################################################################################
