#!/bin/bash

bearer="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzSkx6NXRqRU1LZ0hKbGxvdVFRbThHX2s3MkhCUzZfcHdPSHZGYzRmTTFjIn0.eyJleHAiOjE3MDg2ODI4ODMsImlhdCI6MTcwODY4MjU4MywianRpIjoiMjQ1OTMwZGYtYTIyNi00YjBlLWFiMjMtYzJhMjU0ZTU5ODc3IiwiaXNzIjoiaHR0cHM6Ly9hYWkuZGVtby5tZWluYmlsZHVuZ3NyYXVtLmRlL3JlYWxtcy9uYnAtYWFpIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImNkYzhhODZmLWM5Y2EtNDVmMi05MmE3LTQ4NzA5MjRlZmNmYiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImRlMDE5MWFkLTkwZjYtNDA2Yy1iOTcyLWU0ZTY3NzE2MTc4NCIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtbmJwLWFhaSJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImRlMDE5MWFkLTkwZjYtNDA2Yy1iOTcyLWU0ZTY3NzE2MTc4NCI6eyJyb2xlcyI6WyJkYW0tc291cmNlLW93bmVyOmVkdS1zaGFyaW5nLWVkaXRvcmlhbC1uZXR3b3JrIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im5icC1lbm1lc2hlZC1hZGRyZXNzIGhvbWVpZHAiLCJjbGllbnRIb3N0IjoiMTAuNjUuOC43IiwiY2xpZW50QWRkcmVzcyI6IjEwLjY1LjguNyIsImNsaWVudF9pZCI6ImRlMDE5MWFkLTkwZjYtNDA2Yy1iOTcyLWU0ZTY3NzE2MTc4NCJ9.e3zSsDW2WzWwEHNJ-Za2SfGcDh1aCeEyEtbht3K7Sj5oPDxRAV5utLDV5jXob4vUu9B3puYU9uAs10_zc1fHIq-Fbk7OxkDn-IPcVg8A0BV5WCECCYDkmt6WdYZyUaiKQNCXMlAQGqwYS4UuZfPhKm5r5M2Kq-_JGxeTItKu_R3B7zHlLZTDXHgYs4Z1TlDLlOI0Wbj0501Y13e4PcOQo_JbmM2TZMFGxcx2kghzoIhkhxJay6bpoTEbKIb4Wbcvj1jaTUhK-NQ8ej2Qxld6n1moT-PeUaEPGaRUkCu1sekBA_4invY458T-Sedr2Ts6nWHT9Kr1if2z2H2ywY5ykA"

curl -X 'PUT' 'https://dam.demo.meinbildungsraum.de/push-connector/api/lom/4f507736-5d91-428e-abea-af7944652e17' \
-H 'accept: application/json' \
-H "Authorization: Bearer $bearer" \
-H 'Content-Type: application/json' \
-d '{
"sourceId": "a8e9d0a8-b4ec-4b55-a27f-59bf99da3e66",
"metadata": "<lom xmlns=\"http://ltsc.ieee.org/xsd/LOM\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://ltsc.ieee.org/xsd/LOM http://ltsc.ieee.org/xsd/lomv1.0/lom.xsd\"> <general> <identifier> <catalog>local</catalog> <entry>6</entry> </identifier> <title> <string language=\"en\">Functions of a Complex Variable</string> </title> <language>en</language> <description> <string language=\"en\">This is an advanced undergraduate course dealing with calculus in one complex variable with geometric emphasis. Since the course Analysis I (18.100B) is a prerequisite, topological notions like compactness, connectedness, and related properties of continuous functions are taken for granted. This course offers biweekly problem sets with solutions, two term tests and a final exam, all with solutions.</string> </description> <keyword> <string>Mathematics</string> <string>Topology and Geometry</string> <string>Calculus</string> <string language=\"en\">Mathematical Analysis</string> </keyword> <structure/> <aggregationLevel/> </general> <lifeCycle> <version><string>1.1</string></version> <status/> <contribute> <role> <value>author</value> </role> <entity>BEGIN:VCARD VERSION:3.0 FN:Massachusetts Institute of Technology N:;;;; ORG:Massachusetts Institute of Technology X-ROR:https://ror.org/042nb2s44 END:VCARD</entity> <entity>BEGIN:VCARD VERSION:3.0 FN:Sigurdur Helgason N:Helgason;Sigurdur;;; TITLE:Prof. END:VCARD</entity> </contribute> </lifeCycle> <metaMetadata/> <technical> <format>text/html</format> <location>https://repository.staging.openeduhub.net/edu-sharing/components/render/03dae343-96f3-4fa0-8f45-3cf55b885353</location> </technical> <educational> <learningResourceType> <value>exercise</value> </learningResourceType> <context> <value>higher education</value> </context> <intendedEndUserRole/> </educational> <rights> <copyrightAndOtherRestrictions> <value>yes</value> </copyrightAndOtherRestrictions> <description> <string language=\"de\">https://creativecommons.org/licenses/by-nc-sa/4.0/deed.de</string> </description> <cost><value>no</value></cost> </rights> <classification> <purpose> <source>LOMv1.0</source> <value>discipline</value> </purpose> <keyword> <string language=\"de\"/> </keyword> <taxonPath> <source> <string language=\"x-t-eaf\">EAF Thesaurus</string> </source> <taxon> <id/> </taxon> </taxonPath> </classification> </lom>"
}'