apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edu_sharing_projects_wlo_nbp_connector.name" . }}-env
  labels: {{ include "edu_sharing_projects_wlo_nbp_connector.labels.app" . | nindent 4 }}
type: Opaque
data:
  EDU_SHARING_USER: "{{ .Values.config.repository.username | b64enc }}"
  EDU_SHARING_PASSWORD: "{{ default .Values.global.password .Values.config.repository.password | b64enc }}"
  spring.security.auth-token: "{{ .Values.config.auth.apiToken | b64enc }}"
  nbp.sourceId: "{{ .Values.config.nbp.sourceId | b64enc }}"
  spring.security.oauth2.client.registration.nbp.client-id: "{{ .Values.config.nbp.oAuth2.clientId | b64enc }}"
  spring.security.oauth2.client.registration.nbp.client-secret: "{{ .Values.config.nbp.oAuth2.clientSecret | b64enc }}"