apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edu_sharing_projects_wlo_nbp_connector.name" . }}-env
  labels: {{ include "edu_sharing_projects_wlo_nbp_connector.labels.app" . | nindent 4 }}
type: Opaque
data:
  EDU_SHARING_USER: "{{ .Values.config.repository.username | b64enc }}"
  EDU_SHARING_PASSWORD: "{{ default .Values.global.password .Values.config.repository.password | b64enc }}"
